- name: Create machines
  hosts: localhost
  connection: local
  vars:
    _size_id: s-1vcpu-1gb
    _region_id: ams3
    _image_id: ubuntu-22-04-x64
    _vpc_name: kubernetes-the-hard-way
    _cidr: 10.240.0.0/24
    deploy: false
  tasks:
    - name: Find kubectl is available local path  # noqa command-instead-of-shell
      ansible.builtin.shell: which kubectl
      check_mode: false
      changed_when: false
      failed_when: kubectl_exists.rc > 0
      register: kubectl_exists

    - name: Assert result of kubectl_exists is true
      ansible.builtin.assert:
        that: kubectl_exists.rc == 0
    - name: Create SSH keypair
      community.crypto.openssh_keypair:
        size: 2048
        path: "{{ lookup('env', 'PWD') }}/id_rsa_k8s_do"
      register: ssh_key
    - name: Add ssh key to digitalocean
      community.digitalocean.digital_ocean_sshkey:
        oauth_token: "{{ lookup('env', 'DO_TOKEN') }}"
        name: "ansible key"
        ssh_pub_key: "{{ ssh_key.public_key }}"
        state: present
      register: do_ssh_key

    - name: Create Digitalocean VPC
      community.digitalocean.digital_ocean_vpc:
        state: present
        description: "VPC for K8s the hard way"
        name: "{{ _vpc_name }}"
        region: "{{ _region_id }}"
        ip_range: "{{ _cidr }}"
      register: do_vpc

    # Add loadbalancer

    - name: Create Controller Machines
      community.digitalocean.digital_ocean_droplet:
        state: present
        name: "kube-{{ item }}"
        size: "{{ _size_id }}"
        region_id: "{{ _region_id }}"
        image: "{{ _image_id }}"
        ssh_keys: "{{ do_ssh_key.data.ssh_key.id }}"
        unique_name: true
        private_networking: true
        monitoring: true
        vpc_uuid: "{{ do_vpc.data.vpc.id }}"
        tags:
          - k8s
          - controller
          - auto_destroy
      register: controller_droplets
      loop: "{{ range(0, 3) | list }}"
      when: deploy | bool

    - name: Create Droplet firewall
      community.digitalocean.digital_ocean_firewall:
        # droplet_ids: controller_droplets.
        state: present
        name: '{{ _vpc_name }}-firewall'
        inbound_rules:
          - protocol: tcp
            ports: 22
            sources:
              addresses: ["0.0.0.0/0"]
          - protocol: tcp
            ports: 6443
            sources:
              addresses: ["0.0.0.0/0"]
          - protocol: icmp
            ports: "1-65535"
            sources:
              addresses: ["0.0.0.0/0"]
        outbound_rules:
          - protocol: "tcp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
          - protocol: "udp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
          - protocol: "icmp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
        tags: k8s
      register: do_firewall

- name: Destroy
  hosts: localhost
  connection: local
  vars:
    _size_id: s-1vcpu-1gb
    _region_id: ams3
    _image_id: ubuntu-22-04-x64
    _vpc_name: kubernetes-the-hard-way
    deploy: false
    destroy: false
  tasks:
    - name: Get medieval
      when: destroy | bool
      block:
        # - name: Look up all Droplets tagged with auto-destroy

        - name: Remove Controller Machines
          community.digitalocean.digital_ocean_droplet:
            state: absent
            region_id: "{{ _region_id }}"
            vpc_uuid: "{{ do_vpc.data.vpc.id }}"
            name: "kube-{{ item }}"
            unique_name: true
            tags:
              - auto-destroy
          loop: "{{ range(0, 3) | list }}"

        - name: Destroy ssh key
          community.digitalocean.digital_ocean_sshkey:
            oauth_token: "{{ lookup('env', 'DO_TOKEN') }}"
            name: "ansible key"
            ssh_pub_key: "{{ ssh_key.public_key }}"
            state: absent
        - name: Remove local SSH keys
          community.crypto.openssh_keypair:
            state: absent
            path: "{{ lookup('env', 'PWD') }}/id_rsa_k8s_do"

        - name: Wait for VPC to contain zero members
          community.digitalocean.digital_ocean_vpc_info:
            members: true
            name: "{{ _vpc_name }}"
          register: vpc_cleanup
          until: vpc_cleanup.data.members | length == 0
          retries: 10
          delay: 5


        - name: Destroy VPC
          community.digitalocean.digital_ocean_vpc:
            state: absent
            name: "{{ _vpc_name }}"
            region: "{{ _region_id }}"
