- name: Create machines
  hosts: localhost
  connection: local
  tags:
    - deploy
  tasks:
    - name: Get vars
      ansible.builtin.include_vars: defaults/main.yml

    - name: Find kubectl is available local path  # noqa command-instead-of-shell
      ansible.builtin.shell: which kubectl
      check_mode: false
      changed_when: false
      failed_when: kubectl_exists.rc > 0
      register: kubectl_exists

    - name: Assert result of kubectl_exists is true
      ansible.builtin.assert:
        that: kubectl_exists.rc == 0

    - name: DigitalOcean
      ansible.builtin.include_tasks: tasks/digitalocean.yml

    - name: PKI
      ansible.builtin.include_tasks: tasks/pki.yml

    - name: Controllers
      ansible.builtin.include_tasks: tasks/controllers.yml

    - name: Workers
      ansible.builtin.include_tasks: tasks/workers.yml
