- name: Ensure local ca dir is present
  ansible.builtin.file:
    path: "{{ lookup('env', 'PWD') }}/ca"
    state: directory
    mode: "0700"

- name: Create private key for CA
  community.crypto.openssl_privatekey:
    size: 2048
    type: RSA
    path: "{{ lookup('env', 'PWD') }}/ca/ca-key.pem"

- name: Create certificate signing request (CSR) for CA
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ lookup('env', 'PWD') }}/ca/ca-key.pem"
    organization_name: Kubernetes
    organizational_unit_name: CA
    country_name: IT
    state_or_province_name: Sicily
    locality_name: Catania
    # see https://www.openssl.org/docs/manmaster/man5/x509v3_config.html
    key_usage:
      - digitalSignature
      - keyEncipherment
      - keyCertSign
      - dataEncipherment
    extended_key_usage:
      - serverAuth
      - clientAuth
  register: ca_csr

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ lookup('env', 'PWD') }}/ca/ca-cert.pem"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ lookup('env', 'PWD') }}/ca/ca-key.pem"
    provider: selfsigned

- name: Ensure certs directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'PWD') }}/certs"
    state: directory
    mode: "0700"
